set nocompatible          " Use Vim settings, rather then Vi settings (much better!).
set tabstop=2             " Tabs are 2 character
set shiftwidth=2          " (Auto)indent uses 2 characters
set expandtab             " spaces instead of tabs
set autoindent            " Always set auto indenting on
set number                " show line numbers
set hlsearch              " highlight the searchterms
set incsearch             " jump to the matches while typing
set ignorecase            " ignore case while searching
set history=50            " history
set undolevels=1000       " 1000 undo levels
set ruler                 " show a ruler

syntax on                 " syntax highlight
colorscheme vividchalk    " Color scheme selection

set laststatus=2          " always show status line
set statusline=%F\ %(\[%M%R%H]%)%=\ %4l,%02c%2V\ %P%* " full path to file, location in file

" When editing a file, always jump to the last known cursor position.
" Don't do it when the position is invalid or when inside an event handler
" (happens when dropping a file on gvim).
autocmd BufReadPost *
  \ if line("'\"") > 0 && line("'\"") <= line("$") |
  \   exe "normal g`\"" |
  \ endif

